# Generated by Django 4.0.6 on 2022-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bodypartTrained', models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Tricep', 'Tricep'), ('Bicep', 'Bicep')], max_length=20)),
            ],
        ),
    ]
