# Generated by Django 4.0.6 on 2022-07-20 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
