# Generated by Django 4.0.6 on 2022-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_workout_created_workout_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.CharField(default='NO', max_length=5),
        ),
    ]
