# Generated by Django 4.0.6 on 2022-07-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_workout_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodypart', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='bodypart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bodypart'),
        ),
    ]
