# Generated by Django 4.0.6 on 2022-07-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bodypart_exercise_bodypart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='bodypartTrained',
        ),
    ]
