# Generated by Django 4.0.6 on 2022-07-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_exercise_bodyparttrained'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodypart',
            old_name='bodypart',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='bodypart',
            new_name='bodypart_trained',
        ),
    ]
