# Generated by Django 4.0.6 on 2022-07-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_bodypart_bodypart_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfmadeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bodypart_trained', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bodypart')),
            ],
        ),
    ]
