# Generated by Django 4.0.6 on 2022-07-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_selfmadeexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmadeexercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
