# Generated by Django 4.0.6 on 2022-07-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_selfmadeexercise_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfmadeExercise',
            new_name='OwnExercise',
        ),
    ]
