# Generated by Django 4.0.6 on 2022-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_selfmadeexercise_ownexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='ownexercise',
            field=models.ManyToManyField(to='base.ownexercise'),
        ),
    ]
