# Generated by Django 4.0.6 on 2022-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_workout_ownexercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='user',
            name='completed_knowledge_statement',
            field=models.BooleanField(default=False),
        ),
    ]
