# Generated by Django 4.0.6 on 2022-07-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_statements_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='statements_list',
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
