# Generated by Django 4.0.6 on 2022-07-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_enctopic_encitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encitem',
            name='topic',
        ),
        migrations.AddField(
            model_name='encitem',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.enctopic'),
        ),
    ]
