# Generated by Django 4.0.6 on 2022-07-26 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_encitem_topic_encitem_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encitem',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='encitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
