# Generated by Django 4.0.6 on 2022-08-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_shopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
