# Generated by Django 4.0.6 on 2022-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_shopitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemsection',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
