# Generated by Django 4.0.6 on 2022-08-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_shopitemsection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='base.shopitem')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='shoppingcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shoppingcart'),
        ),
    ]
