# Generated by Django 4.0.6 on 2022-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_shoppingcart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='item',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='base.shopitem'),
        ),
    ]
